name: garda-test
dependencies:
  - python=3.7
  - numpy=1.21.*
  - conda-forge::cudatoolkit=11.3.*
  - tensorboard=2.10.*
  - scikit-learn=1.0.*
  - pandas=1.3.*
  - conda-forge::pillow=8.3.*
  - setuptools=59.5.*
  - pip
  - pip:
    - simpleitk